#ifndef TBOT_CONNECT_STATE_H_
#define TBOT_CONNECT_STATE_H_

#include <cstddef>

enum class TbotConnectState {
    BOOT,
    WIFI_NOT_CONFIGURED,
    WIFI_CONNECTING,
    WIFI_CONNECTED,
    BOOTSTRAP_FETCHING,
    CLAIM_AVAILABLE,
    CLAIM_WAITING_CONFIRM,
    CLAIM_CONFIRM_TIMEOUT,
    CLAIM_CONFIRMED,
    CLAIMED,
    QR_CODE_VISIBLE_FALLBACK,
    PAIRING_CODE_VISIBLE_FALLBACK,
    BLE_SETUP_ADVERTISING,
    BLE_SETUP_TIMEOUT,
    AP_SETUP_ACTIVE,
    AP_SETUP_TIMEOUT,
    BACKEND_CONNECTING,
    ONLINE,
    OFFLINE_RETRY,
    OTA_UPDATING,
    ERROR_RECOVERABLE,
};

enum class TbotSetupRadioState {
    Off,
    Advertising,
    Active,
};

enum class TbotRetryPolicy {
    None,
    Immediate,
    Backoff,
    UserRetry,
    WindowExpires,
};

enum class TbotRecoveryAction {
    None,
    OpenApp,
    StartWifiSetup,
    RetryWifi,
    RetryBootstrap,
    RetryClaim,
    PressRobotButton,
    ShowQrFallback,
    ShowPairingCodeFallback,
    StopBleAndWaitForUser,
    StopApAndWaitForUser,
    ReconnectBackend,
    RetryOta,
    HoldButtonToRetry,
};

struct TbotConnectStateSpec {
    TbotConnectState state;
    const char* screen_text;
    int timeout_seconds;
    TbotRetryPolicy retry_policy;
    TbotSetupRadioState ble_state;
    TbotSetupRadioState ap_state;
    TbotConnectState next_states[4];
    std::size_t next_state_count;
    TbotRecoveryAction recovery_action;
};

static constexpr TbotConnectStateSpec kTbotConnectStateSpecs[] = {
    {
        .state = TbotConnectState::BOOT,
        .screen_text = "Starting",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::Immediate,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::WIFI_NOT_CONFIGURED, TbotConnectState::WIFI_CONNECTING},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::None,
    },
    {
        .state = TbotConnectState::WIFI_NOT_CONFIGURED,
        .screen_text = "Open TBot app",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::UserRetry,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::BLE_SETUP_ADVERTISING, TbotConnectState::AP_SETUP_ACTIVE},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::StartWifiSetup,
    },
    {
        .state = TbotConnectState::WIFI_CONNECTING,
        .screen_text = "Connecting Wi-Fi...",
        .timeout_seconds = 60,
        .retry_policy = TbotRetryPolicy::Backoff,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::WIFI_CONNECTED, TbotConnectState::WIFI_NOT_CONFIGURED},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::RetryWifi,
    },
    {
        .state = TbotConnectState::WIFI_CONNECTED,
        .screen_text = "Wi-Fi connected",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::Immediate,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::BOOTSTRAP_FETCHING, TbotConnectState::BACKEND_CONNECTING},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::RetryBootstrap,
    },
    {
        .state = TbotConnectState::BOOTSTRAP_FETCHING,
        .screen_text = "Loading setup...",
        .timeout_seconds = 30,
        .retry_policy = TbotRetryPolicy::Backoff,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::CLAIM_AVAILABLE, TbotConnectState::ERROR_RECOVERABLE},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::RetryBootstrap,
    },
    {
        .state = TbotConnectState::CLAIM_AVAILABLE,
        .screen_text = "Ready to connect",
        .timeout_seconds = 300,
        .retry_policy = TbotRetryPolicy::WindowExpires,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::CLAIM_WAITING_CONFIRM, TbotConnectState::QR_CODE_VISIBLE_FALLBACK, TbotConnectState::PAIRING_CODE_VISIBLE_FALLBACK},
        .next_state_count = 3,
        .recovery_action = TbotRecoveryAction::OpenApp,
    },
    {
        .state = TbotConnectState::CLAIM_WAITING_CONFIRM,
        .screen_text = "Allow connection? Press button.",
        .timeout_seconds = 60,
        .retry_policy = TbotRetryPolicy::WindowExpires,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::CLAIM_CONFIRMED, TbotConnectState::CLAIM_CONFIRM_TIMEOUT},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::PressRobotButton,
    },
    {
        .state = TbotConnectState::CLAIM_CONFIRM_TIMEOUT,
        .screen_text = "Setup expired",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::UserRetry,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::CLAIM_AVAILABLE, TbotConnectState::QR_CODE_VISIBLE_FALLBACK},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::RetryClaim,
    },
    {
        .state = TbotConnectState::CLAIM_CONFIRMED,
        .screen_text = "Connection allowed",
        .timeout_seconds = 30,
        .retry_policy = TbotRetryPolicy::Backoff,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::CLAIMED, TbotConnectState::ERROR_RECOVERABLE},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::RetryClaim,
    },
    {
        .state = TbotConnectState::CLAIMED,
        .screen_text = "Robot claimed",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::Immediate,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::BACKEND_CONNECTING},
        .next_state_count = 1,
        .recovery_action = TbotRecoveryAction::ReconnectBackend,
    },
    {
        .state = TbotConnectState::QR_CODE_VISIBLE_FALLBACK,
        .screen_text = "Scan QR code",
        .timeout_seconds = 300,
        .retry_policy = TbotRetryPolicy::WindowExpires,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::CLAIM_WAITING_CONFIRM, TbotConnectState::PAIRING_CODE_VISIBLE_FALLBACK},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::ShowQrFallback,
    },
    {
        .state = TbotConnectState::PAIRING_CODE_VISIBLE_FALLBACK,
        .screen_text = "Enter pairing code",
        .timeout_seconds = 300,
        .retry_policy = TbotRetryPolicy::WindowExpires,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::CLAIM_WAITING_CONFIRM, TbotConnectState::CLAIM_CONFIRM_TIMEOUT},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::ShowPairingCodeFallback,
    },
    {
        .state = TbotConnectState::BLE_SETUP_ADVERTISING,
        .screen_text = "Searching for device...",
        .timeout_seconds = 300,
        .retry_policy = TbotRetryPolicy::WindowExpires,
        .ble_state = TbotSetupRadioState::Advertising,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::WIFI_CONNECTING, TbotConnectState::BLE_SETUP_TIMEOUT},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::StartWifiSetup,
    },
    {
        .state = TbotConnectState::BLE_SETUP_TIMEOUT,
        .screen_text = "Setup expired",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::UserRetry,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::WIFI_NOT_CONFIGURED, TbotConnectState::AP_SETUP_ACTIVE},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::StopBleAndWaitForUser,
    },
    {
        .state = TbotConnectState::AP_SETUP_ACTIVE,
        .screen_text = "Open TBot app",
        .timeout_seconds = 600,
        .retry_policy = TbotRetryPolicy::WindowExpires,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Active,
        .next_states = {TbotConnectState::WIFI_CONNECTING, TbotConnectState::AP_SETUP_TIMEOUT},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::StartWifiSetup,
    },
    {
        .state = TbotConnectState::AP_SETUP_TIMEOUT,
        .screen_text = "Hold button 5s to retry",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::UserRetry,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::WIFI_NOT_CONFIGURED, TbotConnectState::BLE_SETUP_ADVERTISING},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::StopApAndWaitForUser,
    },
    {
        .state = TbotConnectState::BACKEND_CONNECTING,
        .screen_text = "Connecting...",
        .timeout_seconds = 30,
        .retry_policy = TbotRetryPolicy::Backoff,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::ONLINE, TbotConnectState::OFFLINE_RETRY},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::ReconnectBackend,
    },
    {
        .state = TbotConnectState::ONLINE,
        .screen_text = "Connected",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::None,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::OFFLINE_RETRY, TbotConnectState::OTA_UPDATING},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::None,
    },
    {
        .state = TbotConnectState::OFFLINE_RETRY,
        .screen_text = "Server unavailable. Retrying...",
        .timeout_seconds = 90,
        .retry_policy = TbotRetryPolicy::Backoff,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::BACKEND_CONNECTING, TbotConnectState::ERROR_RECOVERABLE},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::ReconnectBackend,
    },
    {
        .state = TbotConnectState::OTA_UPDATING,
        .screen_text = "Updating...",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::None,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::BOOT, TbotConnectState::ERROR_RECOVERABLE},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::RetryOta,
    },
    {
        .state = TbotConnectState::ERROR_RECOVERABLE,
        .screen_text = "Hold button 5s to retry",
        .timeout_seconds = 0,
        .retry_policy = TbotRetryPolicy::UserRetry,
        .ble_state = TbotSetupRadioState::Off,
        .ap_state = TbotSetupRadioState::Off,
        .next_states = {TbotConnectState::BOOT, TbotConnectState::WIFI_NOT_CONFIGURED},
        .next_state_count = 2,
        .recovery_action = TbotRecoveryAction::HoldButtonToRetry,
    },
};

static constexpr std::size_t kTbotConnectStateSpecCount =
    sizeof(kTbotConnectStateSpecs) / sizeof(kTbotConnectStateSpecs[0]);

#endif  // TBOT_CONNECT_STATE_H_
