"""Convert eye PNGs into a single LVGL C source file (RGB565 little-endian).

Usage (from this folder):
    python convert_eyes.py
Writes: eyes_images.c next to this script.

Output size per image: TARGET_W * TARGET_H * 2 bytes (RGB565).
Total for 6 eyes at 240x180 ≈ 518 KB.
"""

import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET_W = 240
TARGET_H = 180

# Map source PNG filename -> C symbol name
EYES = [
    ("openeyes.png",      "eye_openeyes"),
    ("sleepeyes.png",     "eye_sleepeyes"),
    ("halfsleepeyes.png", "eye_halfsleepeyes"),
    ("lefteyes.png",      "eye_lefteyes"),
    ("righteyes.png",     "eye_righteyes"),
    ("lookdoweyes.png",   "eye_lookdoweyes"),
    ("sadeyes.png",       "eye_sadeyes"),
]

# Optional GIF files to embed verbatim as byte arrays. The renderer detects the
# "GIF" magic and routes them through the LVGL GIF decoder.
GIFS = [
    ("happy_eyes_esp32_320x240.gif", "eye_happy_gif"),
]


def to_rgb565_bytes(img):
    """Convert an RGB PIL image to little-endian RGB565 bytes."""
    img = img.convert("RGB")
    px = img.tobytes()
    out = bytearray(len(px) // 3 * 2)
    for i in range(len(px) // 3):
        r, g, b = px[i * 3], px[i * 3 + 1], px[i * 3 + 2]
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        out[i * 2] = v & 0xFF
        out[i * 2 + 1] = (v >> 8) & 0xFF
    return bytes(out)


def emit_c_array(name, data):
    lines = []
    lines.append(f"static const")
    lines.append(f"LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST")
    lines.append(f"uint8_t {name}_map[] = {{")
    PER_LINE = 32
    for i in range(0, len(data), PER_LINE):
        chunk = data[i:i + PER_LINE]
        lines.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_image_dsc_t {name} = {{")
    lines.append(f"  .header.magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append(f"  .header.cf = LV_COLOR_FORMAT_RGB565,")
    lines.append(f"  .header.flags = 0,")
    lines.append(f"  .header.w = {TARGET_W},")
    lines.append(f"  .header.h = {TARGET_H},")
    lines.append(f"  .header.stride = {TARGET_W * 2},")
    lines.append(f"  .data_size = sizeof({name}_map),")
    lines.append(f"  .data = {name}_map,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    out_path = os.path.join(HERE, "eyes_images.c")
    parts = []
    parts.append("/*")
    parts.append(" * eyes_images.c — auto-generated by convert_eyes.py")
    parts.append(f" * Each image: {TARGET_W}x{TARGET_H} RGB565")
    parts.append(" */")
    parts.append("")
    parts.append("#if defined(LV_LVGL_H_INCLUDE_SIMPLE)")
    parts.append('#include "lvgl.h"')
    parts.append("#else")
    parts.append('#include "lvgl/lvgl.h"')
    parts.append("#endif")
    parts.append("")
    parts.append("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    parts.append("#define LV_ATTRIBUTE_MEM_ALIGN")
    parts.append("#endif")
    parts.append("")

    total = 0
    for fname, sym in EYES:
        src = os.path.join(HERE, fname)
        if not os.path.exists(src):
            raise SystemExit(f"Missing: {src}")
        img = Image.open(src)
        # Resize keeping aspect, then pad to exact target size with black bg
        img.thumbnail((TARGET_W, TARGET_H), Image.LANCZOS)
        canvas = Image.new("RGB", (TARGET_W, TARGET_H), (0, 0, 0))
        ox = (TARGET_W - img.size[0]) // 2
        oy = (TARGET_H - img.size[1]) // 2
        canvas.paste(img, (ox, oy))
        data = to_rgb565_bytes(canvas)
        total += len(data)
        parts.append(f"/* --- {fname} ({img.size[0]}x{img.size[1]} -> padded {TARGET_W}x{TARGET_H}) --- */")
        parts.append(emit_c_array(sym, data))
        print(f"  {fname}: {len(data)} bytes -> {sym}")

    # Embed GIFs as raw bytes. Wrapped in LvglRawImage on the C++ side; the GIF
    # magic ("GIF") triggers the LVGL GIF decoder path automatically.
    for fname, sym in GIFS:
        src = os.path.join(HERE, fname)
        if not os.path.exists(src):
            print(f"  (skip) GIF missing: {src}")
            continue
        with open(src, "rb") as f:
            data = f.read()
        total += len(data)
        parts.append(f"/* --- {fname} (raw GIF, {len(data)} bytes) --- */")
        parts.append(f"const unsigned int {sym}_size = {len(data)};")
        parts.append(f"LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST")
        parts.append(f"const uint8_t {sym}_data[] = {{")
        PER_LINE = 32
        for i in range(0, len(data), PER_LINE):
            chunk = data[i:i + PER_LINE]
            parts.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
        parts.append("};")
        parts.append("")
        print(f"  {fname}: {len(data)} bytes -> {sym}_data[]")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"\nWrote {out_path}")
    print(f"Total image data: {total} bytes ({total // 1024} KB)")


if __name__ == "__main__":
    main()
